### ISSUE TITLE
There is some error. Please help. Thanks :)

### ISSUE THREAD

**Issue by malaobian** [khuangaf/CryptocurrencyPrediction#2]
/Users/michaelma/anaconda3/bin/python3.6 /Users/michaelma/Documents/GitHub/CryptocurrencyPrediction/server.py
Using TensorFlow backend.
/Users/michaelma/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
 * Running on http://localhost:5009/ (Press CTRL+C to quit)
[2018-01-23 15:23:56,668] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michaelma/Documents/GitHub/CryptocurrencyPrediction/server.py", line 96, in index
    return render_template("index.html")
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/michaelma/anaconda3/lib/python3.6/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
127.0.0.1 - - [23/Jan/2018 15:23:56] "GET / HTTP/1.1" 500 -

**Comment by khuangaf** [comment]
The server.py file was originally for building an automatic prediction API, which was moved to this [repository](https://github.com/khuangaf/RealTimeAPI). Please the read the updated README for running the code.
